# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chart', models.IntegerField(default=0)),
                ('award', models.CharField(max_length=200)),
                ('release_year', models.DateField()),
                ('cover', models.URLField(max_length=500)),
                ('votes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('votes', models.IntegerField(default=0)),
                ('logo', models.URLField(null=True)),
                ('members', models.CharField(max_length=500, null=True)),
                ('summary', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chart', models.IntegerField(default=0)),
                ('award', models.CharField(max_length=200)),
                ('chart_date', models.DateField()),
                ('youtube', models.URLField(max_length=500)),
                ('votes', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
