# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
